### ISSUE TITLE
won't work on youtube dash manifest

### ISSUE THREAD

**Issue by erg43hergeg** [emarsden/dash-mpd-cli#2]
I took a link to the dash from a youtube stream `initialPlayer.StreamingData.DashManifestUrl`

`dash-mpd-cli --quality=worst https://manifest.googlevideo.com/api/manifest/dash/expire/1670387314/ei/EsKPY7W1BIGAsfIPhdW4oAs/ip/154.13.53.175/id/W1oorPTCw4A.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/vprv/1/pacing/0/keepalive/yes/fexp/24001373,24007246/itag/0/playlist_type/DVR/sparams/expire,ei,ip,id,source,requiressl,as,vprv,itag,playlist_type/sig/AOq0QJ8wRgIhAJZKg8Xq1kHqjRQysrv_StcyZSThQpBfxEN5kf8Mn89rAiEA1r9oTDr0TQVc-_XLj8DyTg9_aM2vJZuKwXCHzd9BeJs=
`

i got this error:
`Download error: parse error parsing DASH XML: parse error premature end of input`

link to file: [manifest dl](https://transfer.sh/MS2Ilw/manifest)

**Comment by erg43hergeg** [comment]
with this tool everything works https://github.com/nilaoda/N_m3u8DL-RE

**Comment by emarsden** [comment]
Thanks for your report. 

There was indeed a bug in the parsing of certain xs:datetime fields in manifests, when the timezone was not specified. This is now fixed in the dash-mpd-rs library used by dash-mpd-cli, though not currently in the released version of the library until I am able to run more non-regression checks. The YouTube URL has now expired; are you able to check (by rebuilding dash-mpd-cli with the git path) that this fixes the problem? 

(Please note however that this YouTube URL is a "dynamic" MPD, generally used for live streaming, and this library is not currently able to download this type of content, it can only handle "static" MPDs used for VOD.)
