### ISSUE TITLE
How can I download MPD with the license URL?

### ISSUE THREAD

**Issue by neosarchizo** [emarsden/dash-mpd-cli#44]
I have a MPD link that I want to download and I also know the license URL.
I can watch it by [this chrome extension](https://chrome.google.com/webstore/detail/cjfbmleiaobegagekpmlhmaadepdeedn).
How can I download the MPD file?

**Comment by emarsden** [comment]
You say "dash-mpd-cli <mpd-url>". 

I assume since you refer to a license URL that the media content has DRM, in which can you'll need to provide the license key with the --key argument. Finding the key is not something we can discuss here, you may want to read some threads in the forums at videohelp.com.
