### ISSUE TITLE
HTTP Header referer cannot set when download segments

### ISSUE THREAD

**Issue by yoyo890121** [emarsden/dash-mpd-cli#46]
HTTP Header referer cannot work when download segments
`--referer` only work when get .mpd , but not work when download segments

**Comment by emarsden** [comment]
This is true; segment downloads sets the referer header to the MPD manifest (potentially updated if there is an HTTP redirect or if a <Location> element is specified in the MPD). That's because they are the true referer for these segments. Also, you can't really anticipate from the commandline what the correct referer should be, if an HTTP redirect or Location-based redirect occurs.

Can you explain why this is a problem for your usage?

**Comment by yoyo890121** [comment]
Some site will block HTTP connection when referer is not correct.
I used the other tool to try to GET segments, and it can work when set specific HTTP Header referer.
But the site returned HTTP 4XX when did not set HTTP Header referer.

**Comment by emarsden** [comment]
Can you provide the details (privately, if you prefer)? I am having trouble understanding how a normal client would know what referer to send to the server, if it isn't the referer of the MPD manifest.

**Comment by emarsden** [comment]
Thanks, this is hopefully fixed in the latest release. Setting the referer should now allow dash-mpd-cli to behave more similarly to a web browser displaying DASH video.

**Comment by yoyo890121** [comment]
I tried v0.2.14, but it still the same behavior.
